---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - tzcronjobber.kkothule.io
  resources:
  - tzcronjobbers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tzcronjobber.kkothule.io
  resources:
  - tzcronjobbers/finalizers
  verbs:
  - update
- apiGroups:
  - tzcronjobber.kkothule.io
  resources:
  - tzcronjobbers/status
  verbs:
  - get
  - patch
  - update
