# permissions for end users to view tzcronjobbers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tzcronjobber-viewer-role
rules:
- apiGroups:
  - tzcronjobber.kkothule.io
  resources:
  - tzcronjobbers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tzcronjobber.kkothule.io
  resources:
  - tzcronjobbers/status
  verbs:
  - get
